
- name: Install trace module
  include_tasks:
    file: trace-block.yaml
  when: trace_module == 'gprofiler'
  loop: "{{ (wl_trace_modules | default('')).split(',') }}"
  loop_control:
    loop_var: trace_module
  ignore_errors: yes

