
    - name: setup port forwarding
      command: "ssh -4 {{ ansible_user }}@{{ ansible_host }} -fNL {{ local_daemon_url }}:/var/run/docker.sock -i {{ ansible_private_key_file }} -o ControlPath={{ control_path }} -M"
      delegate_to: localhost

    - name: inspect images
      command: "docker image inspect {{ item.key }}"
      register: inspect
      with_dict: "{{ wl_docker_images }}"
      become: yes
      become_flags: '-E'
      delegate_to: localhost
      ignore_errors: yes

    - name: copy daemon images to daemon
      command: "skopeo copy --src-tls-verify={{ item.item.value }} --dest-daemon-host=http://localhost:12222 docker-daemon:{{ item.item.key }} docker-daemon:{{ item.item.key }}"
      register: copy_result
      until: copy_result.rc == 0
      retries: 10
      delay: 5
      when: item.rc == 0
      loop: "{{ inspect.results }}"
      delegate_to: localhost
      become: yes
      become_flags: '-E'

    - name: copy registry images to daemon
      command: "skopeo copy {{ skopeo_options | default('') }} --src-tls-verify={{ item.item.value }} --dest-daemon-host=http://{{ local_daemon_url }} docker://{{ item.item.key }} docker-daemon:{{ item.item.key }}"
      register: copy_result
      until: copy_result.rc == 0
      retries: 10
      delay: 5
      when: item.rc != 0
      loop: "{{ inspect.results }}"
      delegate_to: localhost
      become: yes
      become_flags: '-E'

    - name: cancel port forwarding
      command: "ssh -4 {{ ansible_user }}@{{ ansible_host }} -i {{ ansible_private_key_file }} -o ControlPath={{ control_path }} -O exit"
      delegate_to: localhost

