
k8s_kubeadm_options: {}
k8s_kubeadm_options_default:
  ClusterConfiguration:
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    networking:
      podSubnet: "10.244.0.0/16" 
  KubeletConfiguration:
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: KubeletConfiguration
  InitConfiguration:
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: InitConfiguration
    nodeRegistration:
      criSocket: "/var/run/containerd/containerd.sock"

k8s_kubelet_config_path:
  ubuntu: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  centos: /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
  debian: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

