
- name: Read no_proxy
  shell: 
    cmd: "echo $no_proxy"
    executable: /bin/bash
  register: noproxy

- name: Add no-proxy
  blockinfile:
    path: /etc/environment
    block: |
      no_proxy={{ noproxy.stdout_lines | first | default('') }},10.244.0.0/16,10.96.0.0/16,{{ groups['cluster_hosts'] | map('extract', hostvars, ['ansible_host']) | join(',') }}
  become: yes
  ignore_errors: yes

- name: reset ssh connection
  meta: reset_connection

