
- name: remove old versions
  apt:
    name: "{{ item }}"
    state: absent
  ignore_errors: yes
  loop:
    - docker
    - docker-engine
    - docker.io

- name: add software dependencies
  apt:
    name:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    state: present
  ignore_errors: yes
  register: aptrc
  until: aptrc is success
  retries: 10
  delay: 10

- name: add docker GPG key
  apt_key:
    url: "{{ docker_dist_repo }}/linux/ubuntu/gpg"
    state: present
  register: aptrc
  until: aptrc is success
  retries: 10
  delay: 10

- name: get os codename
  shell:
    cmd: ". /etc/os-release; echo $VERSION_CODENAME"
    executable: /bin/bash
  register: codename

- name: add docker repository to apt
  apt_repository:
    repo: "deb {{ docker_dist_repo }}/linux/ubuntu {{ codename.stdout | lower }} stable"
    state: present

- name: install docker
  apt:
    name:
    - "docker-ce={{ docker_version | default(docker_default_version['ubuntu']) }}"
    - "docker-ce-cli={{ docker_cli_version | default(docker_cli_default_version['ubuntu']) }}"
    update_cache: yes
  register: aptrc
  until: aptrc is success
  retries: 10
  delay: 10


