
- name: remove old versions
  yum:
    name: "{{ item }}"
    state: absent
  ignore_errors: yes
  loop: 
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine

- name: Install docker repo
  get_url:
    url: "{{ docker_dist_repo }}/linux/centos/docker-ce.repo"
    dest: "/etc/yum.repos.d/docker-ce.repo"

- name: install docker
  yum:
    name:
      - "docker-ce-{{ docker_version | default(docker_default_version['centos']) }}"
      - "docker-ce-cli-{{ docker_cli_version | default(docker_cli_default_version['centos']) }}"
    state: present
    update_cache: yes
  register: yumrc
  until: yumrc is success
  retries: 10
  delay: 10

