static_vms:
  - &vm1
    ip_address: 10.219.170.167
    user_name: raspadmin
    ssh_private_key: ~/.ssh/id_rsa
    internal_ip: 10.219.170.167
    ssh_port: 22
    install_packages: false
    os_type: "centos8"

vm_spec: &default_single_core
  GCP:
    machine_type: n1-standard-1

docker_pt:
  vm_groups:
    worker:
      vm_spec: *default_single_core
      vm_count: 1
      os_type: "centos8"
      static_vms:
        - *vm1
    controller:
      vm_spec: *default_single_core
      vm_count: 1
      os_type: "centos8"
      static_vms:
        - *vm1
  flags:
    dpt_docker_image: ""
    dpt_docker_dataset: ""
    dpt_docker_options: ""
    dpt_kubernetes_yaml: ""
    dpt_kubernetes_job: ""
    dpt_logs_dir: ""
    dpt_timeout: "28800,300"
    dpt_name: ""
    dpt_script_args: ""
    dpt_cluster_yaml: ""
    dpt_params: ""
    dpt_tunables: ""
    dpt_registry_map: ""
    dpt_namespace: ""
    dpt_trace_mode: ""
# enable the following flags to speed up svrinfo, only for functional validation
#    svrinfo_flags: "--format all"
    trace_vm_groups: "worker"
    sar_flags: "-B -b -d -p -H -I ALL -m ALL -n ALL -q -r ALL -u ALL -P ALL -v -W -w"
