cloud_worker: &cloud_worker
  Tencent:
    machine_type: S5.LARGE8
    zone: ap-shanghai-2
  
cloud_disk_mount_1: &cloud_disk_mount_1
  Tencent:
    mount_point: /mnt/disk1
    disk_type: LOCAL_SSD
    disk_size: 500
    num_striped_disks: 1

cloud_controller: &cloud_controller
  Tencent:
    machine_type: S5.LARGE8
    zone: ap-shanghai-2
  
docker_pt:
  vm_groups:
    worker:
      vm_count: 1
      os_type: "ubuntu2004"
      vm_spec: *cloud_worker
      disk_spec: *cloud_disk_mount_1
    controller:
      vm_count: 1
      os_type: "ubuntu2004"
      vm_spec: *cloud_controller
  flags:
    dpt_docker_image: ""
    dpt_docker_dataset: ""
    dpt_docker_options: ""
    dpt_kubernetes_yaml: ""
    dpt_kubernetes_job: ""
    dpt_logs_dir: ""
    dpt_timeout: ""
    dpt_name: ""
    dpt_script_args: ""
    dpt_cluster_yaml: ""
    dpt_params: ""
    dpt_tunables: ""
    dpt_registry_map: ""
    dpt_namespace: ""
    tencent_boot_disk_size: "500"
    tencent_boot_disk_type: "CLOUD_SSD"
    ssh_options: "-o TCPKeepAlive=yes"
    sar_flags: "-B -b -d -p -H -I ALL -m ALL -n ALL -q -r ALL -u ALL -P ALL -v -W -w"
    docker_dist_repo: "http://mirrors.aliyun.com/docker-ce/linux/ubuntu"
    docker_registry_mirrors: "https://registry.cn-hangzhou.aliyuncs.com"
    k8s_repo_key_url: "http://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg"
    k8s_repo_url: "http://mirrors.aliyun.com/kubernetes/apt"
    k8s_kubeadm_options: "--image-repository=registry.aliyuncs.com/google_containers"
    k8s_image_mirrors: "docker.io/xmchen/node-feature-discovery:v0.10.1,k8s.gcr.io/nfd/node-feature-discovery:v0.10.1"
    enable_rsync: true
    cloud: Tencent
