
- name: force hugepage allocation
  set_fact:
    wl_sysfs: "{{ wl_sysfs | combine({ '/sys/kernel/mm/hugepages/hugepages-' + (label_name.split('-')[3]) + '/nr_hugepages': (label_name.split('=')[0].split('-')[4] | int) }) }}"