
- name: Find Home
  shell:
    cmd: "echo ~{{ ansible_user }}"
    executable: /bin/bash
  register: home

- name: Create docker auth path
  file:
    path: "{{ home.stdout }}/{{ docker_auth_config_json | dirname }}"
    mode: "0700"
    state: directory
  when: docker_auth_reuse

- name: Copy docker auth 
  copy:
    src: "/home/{{ docker_auth_config_json }}"
    dest: "{{ home.stdout }}/{{ docker_auth_config_json }}"
    mode: preserve
    owner: "{{ ansible_user }}"
  when: docker_auth_reuse
  ignore_errors: yes
  become: yes

