
- hosts: localhost
  gather_facts: no
  tasks:

    - name: Breakpoint at cleanup
      include_role:
        name: breakpoint
      vars:
        breakpoint: CleanupStage

- hosts: workload_hosts
  become: true
  gather_facts: no
  tasks:

    - name: Cleanup sequence
      include_role:
        name: cleanup
      when: ((csp | default('static')) == 'static')

