---
- name: "Docker credential helper setup"
  hosts: "localhost"
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - name: "Prepare correct Docker Auth"
      ansible.builtin.include_role:
        name: docker_auth
        tasks_from: main
