
# global k8s facts stored in localhost
- hosts: localhost
  gather_facts: no
  tasks:

  - name: Check cluster status
    include_role:
      name: installation
      tasks_from: check-cluster
    when: ansible_connection != 'winrm'

- hosts: cluster_hosts
  any_errors_fatal: true
  gather_facts: no
  tasks:

  - name: Prepare the cluster
    include_role:
      name: installation
      tasks_from: prepare-cluster
    when: ansible_connection != 'winrm'

- hosts: "{{ ('controller' in groups) | ternary('controller','localhost') }}"
  gather_facts: no
  tasks:

  - name: Create the cluster
    include_role:
      name: installation
      tasks_from: create-cluster
    when: ansible_connection != 'winrm'

- hosts: workload_hosts
  any_errors_fatal: true
  gather_facts: no
  tasks:

  - name: Join workers
    include_role:
      name: installation
      tasks_from: join-workers
    when: ansible_connection != 'winrm'

- hosts: "{{ ('controller' in groups) | ternary('controller','localhost') }}"
  gather_facts: no
  tasks:
  
  - name: Finalize controller
    include_role:
      name: installation
      tasks_from: finalize-controller
    when: ansible_connection != 'winrm'

- hosts: workload_hosts
  any_errors_fatal: true
  gather_facts: no
  tasks:

  - name: Finalize workers
    include_role:
      name: installation
      tasks_from: finalize-workers
    when: ansible_connection != 'winrm'

