
- name: get node name
  shell: |
    kubectl get nodes -o='custom-columns=name:.metadata.name,ip:.status.addresses[?(@.type=="InternalIP")].address' --no-headers | grep -F " {{ hostvars[item]['private_ip'] }}" | cut -f1 -d' '
  register: nodename
  until: nodename.stdout_lines | length > 0
  retries: 5
  delay: 5
  when: hostvars[item]['k8s_node_labels'] | default([]) | length > 0

- name: label the nodes
  command: |
    kubectl label --overwrite node {{ nodename.stdout }} {{ hostvars[item]['k8s_node_labels'] | default([]) | join(' ') }}
  when: hostvars[item]['k8s_node_labels'] | default([]) | length > 0

